name: student
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  intl: ^0.18.0
  flutter_localizations:
    sdk: flutter
  firebase_core: ^3.4.0
  firebase_auth: ^5.2.0
  youtube_player_flutter: ^8.1.1
  youtube_player_iframe: 5.1.2

dev_dependencies:
  intl_utils: ^2.5.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  generate: true
  assets:
    - assets/logo.jpg
    - assets/background.jpg
  uses-material-design: true
