// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3RuWTNVP65B-yxMqGcVjcAJDSYQaeX8A',
    appId: '1:56281974083:web:b0d29b9cb6880a7ae8dbf6',
    messagingSenderId: '56281974083',
    projectId: 'mobile-e2ce1',
    authDomain: 'mobile-e2ce1.firebaseapp.com',
    storageBucket: 'mobile-e2ce1.firebasestorage.app',
    measurementId: 'G-8C7CXTN91X',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCMvVFIFqhXGYnfp6tiObnpqu-bO9JPTk',
    appId: '1:56281974083:ios:a421fca93a2c9579e8dbf6',
    messagingSenderId: '56281974083',
    projectId: 'mobile-e2ce1',
    storageBucket: 'mobile-e2ce1.firebasestorage.app',
    iosBundleId: 'com.example.student',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCCMvVFIFqhXGYnfp6tiObnpqu-bO9JPTk',
    appId: '1:56281974083:ios:a421fca93a2c9579e8dbf6',
    messagingSenderId: '56281974083',
    projectId: 'mobile-e2ce1',
    storageBucket: 'mobile-e2ce1.firebasestorage.app',
    iosBundleId: 'com.example.student',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA3RuWTNVP65B-yxMqGcVjcAJDSYQaeX8A',
    appId: '1:56281974083:web:cf9e304241207a64e8dbf6',
    messagingSenderId: '56281974083',
    projectId: 'mobile-e2ce1',
    authDomain: 'mobile-e2ce1.firebaseapp.com',
    storageBucket: 'mobile-e2ce1.firebasestorage.app',
    measurementId: 'G-5XCZK2BX8Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCA2VzFKan5RultbFRIAgOs8i-QRGKecMg',
    appId: '1:56281974083:android:bd2a349279c21e9ee8dbf6',
    messagingSenderId: '56281974083',
    projectId: 'mobile-e2ce1',
    storageBucket: 'mobile-e2ce1.firebasestorage.app',
  );

}